// client-angular/src/app/features/spare-movement/components/spare-movement-form/spare-movement-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';

interface Airline {
  text: string;
  value: string;
}

interface Store {
  text: string;
  value: string;
}

interface Names {
  text: string;
  value: string;
}

@Component({
  selector: 'app-spare-movement-form',
  templateUrl: './spare-movement-form.component.html',
  styleUrls: ['./spare-movement-form.component.scss'],
})
export class SpareMovementFormComponent implements OnInit {
  spareMovementForm: FormGroup;
  airlines: Airline[] = [
    { text: 'ASL', value: 'ASL' },
    { text: 'CX', value: 'CX' },
    { text: 'LD', value: 'LD' },
    { text: 'PR', value: 'PR' },
  ];
  stores: Store[] = [
    { text: 'BKK', value: 'BKK' },
    { text: 'BKK306', value: 'BKK306' },
  ];
  names: Names[] = [
    { text: 'Boonyarit', value: 'Boonyarit' },
    { text: 'Theerapong', value: 'Theerapong' },
    { text: 'Totsapon', value: 'Totsapon' },
  ];

  onSubmit() {
    console.log(this.spareMovementForm.value);
  }

  constructor() {
    this.spareMovementForm = new FormGroup({
      date: new FormControl(new Date()),
      airline: new FormControl(this.airlines[1].value),
      fltno: new FormControl('', Validators.required),
      acreg: new FormControl(''),
      part: new FormControl(''),
      desc: new FormControl(''),
      serial: new FormControl('NIL'),
      grn: new FormControl(''),
      qty: new FormControl(0),
      store: new FormControl(this.stores[0].value),
      usedBy: new FormControl(''),
    });
  }

  ngOnInit(): void {}
}

<mat-card>
  <p>spare-movement-form</p>
  <form [formGroup]="spareMovementForm" (ngSubmit)="onSubmit()">
    <div fxLayout="row" fxLayout.xs="column" fxLayoutGap="1rem">
      <mat-form-field appearance="outline">
        <mat-label>Date</mat-label>
        <input matInput [matDatepicker]="picker" formControlName="date" />
        <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
        <mat-datepicker #picker></mat-datepicker>
      </mat-form-field>
      <mat-form-field appearance="outline">
        <mat-label>Airline</mat-label>
        <mat-select formControlName="airline">
          <mat-option *ngFor="let airline of airlines" [value]="airline.value">
            {{ airline.text }}
          </mat-option>
        </mat-select>
      </mat-form-field>
      <mat-form-field appearance="outline">
        <mat-label>Flt No.</mat-label>
        <input matInput formControlName="fltno" />
      </mat-form-field>
      <mat-form-field appearance="outline">
        <mat-label>A/C Reg.</mat-label>
        <input matInput formControlName="acreg" />
      </mat-form-field>
    </div>
    <div fxLayout="column">
      <mat-form-field appearance="outline">
        <mat-label>Part No.</mat-label>
        <input matInput formControlName="part" />
      </mat-form-field>
      <mat-form-field appearance="outline">
        <mat-label>Description</mat-label>
        <input matInput formControlName="desc" />
      </mat-form-field>
    </div>
    <div fxLayout="row" fxLayout.xs="column" fxLayoutGap="1rem">
      <mat-form-field appearance="outline" fxFlex="grow">
        <mat-label>Serial No.</mat-label>
        <input matInput formControlName="serial" />
      </mat-form-field>
      <mat-form-field appearance="outline" fxFlex="grow">
        <mat-label>GRN</mat-label>
        <input matInput formControlName="grn" />
      </mat-form-field>
      <mat-form-field appearance="outline" fxFlex="grow">
        <mat-label>Qty.</mat-label>
        <input matInput formControlName="qty" type="number" />
      </mat-form-field>
    </div>
    <div fxLayout="row" fxLayout.xs="column" fxLayoutGap="1rem">
      <mat-form-field appearance="outline" fxFlex="grow">
        <mat-label>Store</mat-label>
        <mat-select formControlName="store">
          <mat-option *ngFor="let store of stores" [value]="store.value">
            {{ store.text }}
          </mat-option>
        </mat-select>
      </mat-form-field>
      <mat-form-field appearance="outline" fxFlex="grow">
        <mat-label>Used By</mat-label>
        <mat-select formControlName="usedBy" name="usedBy">
          <mat-option *ngFor="let name of names" [value]="name.value">
            {{ name.text }}
          </mat-option>
        </mat-select>
      </mat-form-field>
    </div>
    <button mat-raised-button color="primary" type="submit">Submit</button>
  </form>
</mat-card>

// client-react/src/components/SpareMovement/SpareMovementForm.js
import { useState } from 'react';

import {
  Button,
  Card,
  CardActions,
  CardContent,
  Grid
} from '@material-ui/core';
import { makeStyles } from '@material-ui/core/styles';

import InputDate from '../Shared/InputDate';
import InputRadioGroup from '../Shared/InputRadioGroup';
import InputSelect from '../Shared/InputSelect';
import InputText from '../Shared/InputText';

const useStyles = makeStyles(theme => ({
  root: {
    width: '100%',
    maxWidth: 768,
    margin: '0 auto',
    padding: theme.spacing(2)
  },
  cardActions: {
    padding: theme.spacing(2),
    justifyContent: 'space-between'
  }
}));

const SpareMovementForm = () => {
  const classes = useStyles();
  const [dateInput, setDateInput] = useState(new Date());
  const [formInput, setFormInput] = useState({
    airline: 'CX',
    fltno: '',
    reg: '',
    part: '',
    desc: '',
    type: 'consumable',
    serial: 'NIL',
    grn: '',
    qty: 0,
    store: 'BKK',
    usedBy: ''
  });

  const nameItems = [
    { text: 'Boonyarnt', value: 'Boonyarit' },
    { text: 'Theerapong', value: 'Theerapong' },
    { text: 'Totsapon', value: 'Totsapon' }
  ];

  const typeItems = [
    { text: 'Consumable', value: 'consumable' },
    { text: 'Return', value: 'return' },
    { text: 'Fluid', value: 'fluid' }
  ];

  const onDateChangeHandler = date => {
    setDateInput(date);
  };

  const onInputChangeHandler = e => {
    const { target } = e;
    const { name, value } = target;

    setFormInput({
      ...formInput,
      [name]: value
    });
  };

  const onFormSubmit = e => {
    e.preventDefault();

    console.log({ ...formInput, date: dateInput });

    setFormInput({
      airline: 'CX',
      fltno: '',
      reg: '',
      part: '',
      desc: '',
      type: 'consumable',
      serial: 'NIL',
      grn: '',
      qty: 0,
      store: 'BKK',
      usedBy: ''
    });
    setDateInput(new Date());
  };

  return (
    <form onSubmit={onFormSubmit}>
      <Card className={classes.root}>
        <CardContent>
          <Grid container spacing={2}>
            <Grid item xs={12} sm={3}>
              <InputDate
                name="date"
                value={dateInput}
                onDateChangeHandler={onDateChangeHandler}
              />
            </Grid>
            <Grid item xs={12} sm={3}>
              <InputSelect
                label="Airline"
                name="airline"
                value={formInput.airline}
                onInputChangeHandler={onInputChangeHandler}
              />
            </Grid>
            <Grid item xs={12} sm={3}>
              <InputText
                label="Flt No."
                name="fltno"
                required={true}
                value={formInput.fltno}
                onInputChangeHandler={onInputChangeHandler}
              />
            </Grid>
            <Grid item xs={12} sm={3}>
              <InputText
                label="Reg."
                name="reg"
                required={true}
                value={formInput.reg}
                onInputChangeHandler={onInputChangeHandler}
              />
            </Grid>
          </Grid>
        </CardContent>
        <CardContent>
          <Grid container spacing={2}>
            <Grid item xs={12}>
              <InputText
                label="Part No."
                name="part"
                required={true}
                value={formInput.part}
                onInputChangeHandler={onInputChangeHandler}
              />
            </Grid>
            <Grid item xs={12}>
              <InputText
                label="Description"
                name="desc"
                required={true}
                value={formInput.desc}
                onInputChangeHandler={onInputChangeHandler}
              />
            </Grid>
            <Grid item xs={12}>
              <InputRadioGroup
                label="Type"
                name="type"
                value={formInput.type}
                items={typeItems}
                onInputChangeHandler={onInputChangeHandler}
              />
            </Grid>
            <Grid item xs={12} sm={4}>
              <InputText
                label="Serial No."
                name="serial"
                required={true}
                value={formInput.serial}
                onInputChangeHandler={onInputChangeHandler}
              />
            </Grid>
            <Grid item xs={12} sm={4}>
              <InputText
                label="GRN"
                name="grn"
                required={true}
                value={formInput.grn}
                onInputChangeHandler={onInputChangeHandler}
              />
            </Grid>
            <Grid item xs={12} sm={4}>
              <InputText
                label="Qty"
                name="qty"
                type="number"
                required={true}
                value={formInput.qty}
                onInputChangeHandler={onInputChangeHandler}
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <InputSelect
                label="Store"
                name="store"
                items={[
                  { text: 'BKK', value: 'BKK' },
                  { text: 'BKK306', value: 'BKK306' }
                ]}
                value={formInput.store}
                onInputChangeHandler={onInputChangeHandler}
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <InputSelect
                label="Used By"
                name="usedBy"
                required={true}
                items={nameItems}
                value={formInput.usedBy}
                onInputChangeHandler={onInputChangeHandler}
              />
            </Grid>
          </Grid>
        </CardContent>
        <CardActions className={classes.cardActions}>
          <Button variant="contained" color="primary" type="submit">
            Submit
          </Button>
          <Button variant="contained">Close</Button>
        </CardActions>
      </Card>
    </form>
  );
};

export default SpareMovementForm;
